### Makefile pour HTK_Search => gregory.senay@univ-avignon.fr

### Compilateur et Options 
CC=g++
CFLAGS=-W
LDFLAGS=
DLIBS=
ICCFLAGS= -O3

PROG = HTK_Search
SRC = HTK_Search.cpp

all: $(PROG)
	$(CC) $(CFLAGS) -o $(PROG) $(SRC)
icc:
	icc $(ICCFLAGS) $(SRC) -o $(PROG).icc