### Makefile pour SearchOnAcousticMesh => gregory.senay@univ-avignon.fr

### Compilateur et Options 
CC=g++
CFLAGS=-W
LDFLAGS=
DLIBS=
ICCFLAGS= -O3

PROG = SearchOnAcousticMesh
SRC = SearchOnAcousticMesh.cpp

all: $(PROG)
	$(CC) $(CFLAGS) -o $(PROG) $(SRC)
icc:
	icc $(ICCFLAGS) $(SRC) -o $(PROG).icc